name: newpipeline  #pipeline name hota hai

on:                 #Trigger
  workflow_dispatch:    # Matlab Manual trigger hota hai

jobs:                   # Jobs kya chalana hai
  myfirstjob:            
    name: init_job        # ye job name hota hai
    runs-on: windows-latest   # ye agent pool hota hai yaha microsoft hosted agent hai
    
    steps:
      - name: myfirst_step     # steps name hota hai
        run: write_host " Hello world"    # kya chalana chahte hai
      
