name: newpipeline  #pipeline name hota hai

on:                 #Trigger
  workflow_dispatch:    # Matlab Manual trigger hota hai

jobs:                   # Jobs kya chalana hai
  myfirstjob:            
    name: Myfirstjob       # ye job name hota hai
    runs-on: windows-latest   # ye agent pool hota hai yaha microsoft hosted agent hai
    
    steps:
      - name: myfirst_step     # steps name hota hai
        run: write-hos " Hello world"    # kya chalana chahte hai
      
  mysecondjob:            
    name: Mysecondjob       # ye job name hota hai
    needs: myfirstjob
    runs-on: ubuntu-slim   # ye agent pool hota hai yaha microsoft hosted agent hai
    
    steps:
      - name: mysecond_step     # steps name hota hai
        run: echo " Hello DevopsInsiders"    # kya chalana chahte hai
